nome = input ('Qual é o seu nome?')
print ('Olá,', nome, '! Seja bem-vindo!')
dianasc = input ('Dia do mês em que você nasceu:')
mesnasc = input ('Mês:')
anonasc = input ('Ano:')
print ('Você nasceu no dia', dianasc, 'de', mesnasc,'de', anonasc, '. Correto?')
